name: ${pluginName}
description: ${project.description}
website: ${project.url}

author: ${pluginAuthor}
version: ${project.version}
api-version: ${apiVersion}
main: ${groupId}.${artifactId}.${mainClass}
